- drop:
    - CTY_IS_POS
    - CTY_CTA_EQUAL
    - CTY_BZN_EQUAL
    - CTY_CTA_DIFF_LT_05
    - CTY_BZN_DIFF_LT_05
    - CTY_CTA_DIFF_LT_10
    - CTY_BZN_DIFF_LT_10
  when_not:
    - CTY_NA

- drop:
    - CTA_IS_POS
    - CTY_CTA_EQUAL
    - CTA_BZN_EQUAL
    - CTY_CTA_DIFF_LT_05
    - CTA_BZN_DIFF_LT_05
    - CTY_CTA_DIFF_LT_10
    - CTA_BZN_DIFF_LT_10
  when_not:
    - CTA_NA

- drop:
    - BZN_IS_POS
    - CTY_BZN_EQUAL
    - CTA_BZN_EQUAL
    - CTY_BZN_DIFF_LT_05
    - CTA_BZN_DIFF_LT_05
    - CTY_BZN_DIFF_LT_10
    - CTA_BZN_DIFF_LT_10
  when_not:
    - BZN_NA



- drop:
    - CTY_CTA_DIFF_LT_05
    - CTY_CTA_EQUAL
  when_not:
    - CTY_CTA_DIFF_LT_10

- drop:
    - CTY_BZN_DIFF_LT_05
    - CTY_BZN_EQUAL
  when_not:
    - CTY_BZN_DIFF_LT_10

- drop:
    - CTA_BZN_DIFF_LT_05
    - CTA_BZN_EQUAL
  when_not:
    - CTA_BZN_DIFF_LT_10




- drop:
    - CTY_CTA_EQUAL
    - CTY_BZN_EQUAL
    - CTY_CTA_DIFF_LT_05
    - CTY_BZN_DIFF_LT_05
    - CTY_CTA_DIFF_LT_10
    - CTY_BZN_DIFF_LT_10
  when_not:
    - CTY_IS_POS


- drop:
    - CTY_CTA_EQUAL
    - CTA_BZN_EQUAL
    - CTY_CTA_DIFF_LT_05
    - CTA_BZN_DIFF_LT_05
    - CTY_CTA_DIFF_LT_10
    - CTA_BZN_DIFF_LT_10
  when_not:
    - CTA_IS_POS

- drop:
    - CTA_BZN_EQUAL
    - CTY_BZN_EQUAL
    - CTY_BZN_DIFF_LT_05
    - CTA_BZN_DIFF_LT_05
    - CTY_BZN_DIFF_LT_10
    - CTA_BZN_DIFF_LT_10
  when_not:
    - BZN_IS_POS
