- drop:
    - GRP_CHN_GENERATION_EQUAL
  when_not:
    - IS_FINITE_GRP_GENERATION
    - IS_FINITE_CHN_GENERATION

- drop:
    - GRP_CHN_CAPACITY_EQUAL
  when_not:
    - IS_FINITE_GRP_CAPACITY
    - IS_FINITE_CHN_CAPACITY
