- drop:
    - GRP_TYP_GENERATION_EQUAL
  when_not:
    - IS_FINITE_GRP_GENERATION
    - IS_FINITE_TYP_GENERATION

- drop:
    - GRP_TYP_CAPACITY_EQUAL
  when_not:
    - IS_FINITE_GRP_CAPACITY
    - IS_FINITE_TYP_CAPACITY
