rules:

- expr: is.finite(group_generation)
  name: IS_FINITE_GRP_GENERATION
- expr: is.finite(type_generation)
  name: IS_FINITE_TYP_GENERATION
- expr: abs(group_generation-type_generation) < 1
  name: GRP_TYP_GENERATION_EQUAL

- expr: is.finite(group_capacity)
  name: IS_FINITE_GRP_CAPACITY
- expr: is.finite(type_capacity)
  name: IS_FINITE_TYP_CAPACITY
- expr: abs(group_capacity-type_capacity) < 1
  name: GRP_TYP_CAPACITY_EQUAL


