AUSTRIA:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

BELGIUM:
- Biomass
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Nuclear
- Solar
- Waste
- Wind Offshore
- Wind Onshore

FRANCE:
- Biomass
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Solar
- Wind Offshore
- Wind Onshore

GERMANY:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

IRELAND:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Other
- Wind Onshore

ITALY:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

LUXEMBOURG:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

NETHERLANDS:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

NORTH_IRELAND:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Other
- Wind Onshore

PORTUGAL:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

SPAIN:
- Biomass
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Nuclear
- Other
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore

SWITZERLAND:
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Nuclear

UK:
- Biomass
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Nuclear
- Other
- Other renewable
- Solar
- Wind Offshore
- Wind Onshore
