AUSTRIA:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear

BELGIUM:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Nuclear

FRANCE:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Nuclear

GERMANY:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear

IRELAND:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat

ITALY:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat

LUXEMBOURG:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear

NETHERLANDS:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear

NORTH_IRELAND:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat

PORTUGAL:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear

SPAIN:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear

SWITZERLAND:
- Nuclear

UK:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Nuclear
