AUSTRIA:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear
- Other

BELGIUM:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Nuclear

FRANCE:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Nuclear
- Other

GERMANY:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear
- Other

IRELAND:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat
- Other

ITALY:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat
- Other

LUXEMBOURG:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear
- Other

NETHERLANDS:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear
- Other

NORTH_IRELAND:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Peat
- Other

PORTUGAL:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear
- Other

SPAIN:
- Fossil Brown coal/Lignite
- Fossil Coal-derived gas
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Fossil Oil shale
- Fossil Peat
- Nuclear
- Other

SWITZERLAND:
- Nuclear

UK:
- Fossil Gas
- Fossil Hard coal
- Fossil Oil
- Nuclear
- Other
