- drop:
    - IS_FINITE_OUTPUT
  when_not:
    - IS_OBS

- drop:
    - IS_NOT_NEG_OUTPUT
  when_not:
    - IS_FINITE_OUTPUT
    - IS_OBS

- drop:
    - OUTPUT_LT_CAPACITY
  when_not:
    - IS_FINITE_OUTPUT
    - IS_NOT_NEG_OUTPUT
    - IS_OBS

