AUSTRIA:
- Hydro Pumped Storage

BELGIUM:
- Hydro Pumped Storage

FRANCE:
- Hydro Pumped Storage

GERMANY:
- Hydro Pumped Storage

IRELAND:
- Hydro Pumped Storage

ITALY:
- Hydro Pumped Storage

LUXEMBOURG:
- Hydro Pumped Storage

NETHERLANDS:
- Hydro Pumped Storage

NORTH_IRELAND:
- Hydro Pumped Storage

PORTUGAL:
- Hydro Pumped Storage

SPAIN:
- Hydro Pumped Storage

SWITZERLAND:
- Hydro Pumped Storage

UK:
- Hydro Pumped Storage
