AUSTRIA:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
BELGIUM:
- Biomass
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Solar
- Waste
- Wind Offshore
- Wind Onshore
FRANCE:
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Solar
- Wind Offshore
- Wind Onshore
- Biomass
GERMANY:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
IRELAND:
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Wind Onshore
- Geothermal
ITALY:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
LUXEMBOURG:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
NETHERLANDS:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
NORTH_IRELAND:
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Wind Onshore
- Geothermal
PORTUGAL:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
SPAIN:
- Biomass
- Geothermal
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
- Marine
- Other renewable
- Solar
- Waste
- Wind Offshore
- Wind Onshore
SWITZERLAND:
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Hydro Water Reservoir
UK:
- Biomass
- Hydro Pumped Storage
- Hydro Run-of-river and poundage
- Other renewable
- Solar
- Wind Offshore
- Wind Onshore
