rules:

- expr: is.finite(CTY)
  name: CTY_NA
- expr: is.finite(CTA)
  name: CTA_NA
- expr: is.finite(BZN)
  name: BZN_NA

- expr: CTY > 0
  name: CTY_IS_POS
- expr: CTA > 0
  name: CTA_IS_POS
- expr: BZN > 0
  name: BZN_IS_POS

- expr: abs(CTY-CTA) < 1
  name: CTY_CTA_EQUAL
- expr: abs(CTY-BZN) < 1
  name: CTY_BZN_EQUAL
- expr: abs(CTA-BZN) < 1
  name: CTA_BZN_EQUAL


- expr: abs(1 - (CTY / CTA) ) < .05
  name: CTY_CTA_DIFF_LT_05
- expr: abs(1 - (CTY / BZN) ) < .05
  name: CTY_BZN_DIFF_LT_05
- expr: abs(1 - (CTA / BZN) ) < .05
  name: CTA_BZN_DIFF_LT_05

- expr: abs(1 - (CTY / CTA) ) < .1
  name: CTY_CTA_DIFF_LT_10
- expr: abs(1 - (CTY / BZN) ) < .1
  name: CTY_BZN_DIFF_LT_10
- expr: abs(1 - (CTA / BZN) ) < .1
  name: CTA_BZN_DIFF_LT_10


- expr: ((CTY - lag(CTY)) / CTY) < .5 & ((lag(CTY) - CTY) / lag(CTY)) < .5
  name: CTY_LAG_LT_50
- expr: ((CTA - lag(CTA)) / CTA) < .5 & ((lag(CTA) - CTA) / lag(CTA)) < .5
  name: CTA_LAG_LT_50
- expr: ((BZN - lag(BZN)) / BZN)  < .5 & ((lag(BZN) - BZN) / lag(BZN)) < .5
  name: BZN_LAG_LT_50

