-
  replace: CTA
  use: CTY
  when_false:
    - CTA_NA
    - CTA_IS_POS
    - CTA_BZN_EQUAL
    - CTA_BZN_DIFF_LT_05
    - CTA_BZN_DIFF_LT_10
    - CTY_CTA_EQUAL
    - CTY_CTA_DIFF_LT_05
    - CTY_CTA_DIFF_LT_10
  when_true:
    - BZN_NA
    - CTY_NA
    - CTY_IS_POS
    - BZN_IS_POS
    - CTY_BZN_EQUAL


-
  replace: CTY
  use: CTA
  country:
  when_false:
    - CTY_NA
    - CTY_IS_POS
    - CTY_CTA_EQUAL
    - CTY_CTA_DIFF_LT_05
    - CTY_CTA_DIFF_LT_10
    - CTY_BZN_EQUAL
    - CTY_BZN_DIFF_LT_05
    - CTY_BZN_DIFF_LT_10
  when_true:
    - BZN_NA
    - CTA_NA
    - CTA_IS_POS
    - BZN_IS_POS
    - CTA_BZN_EQUAL
    
  -
  replace: BZN
  use: CTA
  country:
  when_false:
    - BZN_NA
    - BZN_IS_POS
    - CTA_BZN_EQUAL
    - CTA_BZN_DIFF_LT_05
    - CTA_BZN_DIFF_LT_10
    - CTY_BZN_EQUAL
    - CTY_BZN_DIFF_LT_05
    - CTY_BZN_DIFF_LT_10
  when_true:
    - CTY_NA
    - CTA_NA
    - CTA_IS_POS
    - CTY_IS_POS
    - CTY_CTA_EQUAL


