load:
  validate:
    raw:
      validate: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/load/raw_validate.yml
      false_pos: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/load/raw_fp.yml
    agg:
      validate: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/load/agg_validate.yml
      false_pos: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/load/agg_fp.yml
  correct: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/load/agg_correct.yml

production:
  validate:
    raw:
      validate: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/raw_validate.yml
      false_pos: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/raw_fp.yml
    groupes_raw:
      validate: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/raw_validate.yml
      false_pos: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/raw_fp.yml
    agg:
      validate: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/agg_validate.yml
      false_pos: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/agg_fp.yml
    cmp_type_grp:
      validate: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/compare_validate.yml
      false_pos: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/production/compare_fp.yml

global:
  atc_per_country: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/global/atc_per_country.yml
  production_per_country: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/antaDraft/config/global/production_per_country.yml

